-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.titles
(
    title character varying,
    title_id character varying,
    PRIMARY KEY (title_id)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    emp_no integer,
    emp_title_id character varying,
    first_name character varying,
    last_name character varying,
    birth_date date,
    sex character varying,
    hire_date date,
    PRIMARY KEY (emp_no)
);

CREATE TABLE IF NOT EXISTS public.departments
(
    dept_no character varying,
    dept_name character varying,
    PRIMARY KEY (dept_no)
);

CREATE TABLE IF NOT EXISTS public.dept_manager
(
    dept_no character varying,
    emp_no integer
);

CREATE TABLE IF NOT EXISTS public.dept_emp
(
    emp_no integer,
    dept_no character varying
);

CREATE TABLE IF NOT EXISTS public.salaries
(
    emp_no integer,
    salary integer
);

ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT emp_title_fk FOREIGN KEY (emp_title_id)
    REFERENCES public.titles (title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_manager
    ADD CONSTRAINT emp_no_fk FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_manager
    ADD CONSTRAINT dept_no_fk FOREIGN KEY (dept_no)
    REFERENCES public.departments (dept_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_emp
    ADD CONSTRAINT emp_no FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_emp
    ADD CONSTRAINT dept_no FOREIGN KEY (dept_no)
    REFERENCES public.departments (dept_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.salaries
    ADD CONSTRAINT emp_no_fk FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;